In [23]:
import pandas as pd
import numpy as np

In [25]:
df = pd.read_csv('datasets/daily-min-temperatures.csv', parse_dates=[0])
df

           Date  Temp
0    1981-01-01  20.7
1    1981-01-02  17.9
2    1981-01-03  18.8
3    1981-01-04  14.6
4    1981-01-05  15.8
...         ...   ...
3645 1990-12-27  14.0
3646 1990-12-28  13.6
3647 1990-12-29  13.5
3648 1990-12-30  15.7
3649 1990-12-31  13.0

[3650 rows x 2 columns]

In [27]:
df['month'] = df.Date.dt.month
df['day'] = df.Date.dt.day
# df.set_index('Date', inplace=True)
df

           Date  Temp  month  day
0    1981-01-01  20.7      1    1
1    1981-01-02  17.9      1    2
2    1981-01-03  18.8      1    3
3    1981-01-04  14.6      1    4
4    1981-01-05  15.8      1    5
...         ...   ...    ...  ...
3645 1990-12-27  14.0     12   27
3646 1990-12-28  13.6     12   28
3647 1990-12-29  13.5     12   29
3648 1990-12-30  15.7     12   30
3649 1990-12-31  13.0     12   31

[3650 rows x 4 columns]

In [35]:
for lag, ann in zip(range(3, -1, -1), ['-2', '-1', '0', '+1']):
    df['t'+ann] = df.Temp.shift(lag)
    
df

           Date  Temp  month  day   t-2   t-1    t0   t+1
0    1981-01-01  20.7      1    1   NaN   NaN   NaN  20.7
1    1981-01-02  17.9      1    2   NaN   NaN  20.7  17.9
2    1981-01-03  18.8      1    3   NaN  20.7  17.9  18.8
3    1981-01-04  14.6      1    4  20.7  17.9  18.8  14.6
4    1981-01-05  15.8      1    5  17.9  18.8  14.6  15.8
...         ...   ...    ...  ...   ...   ...   ...   ...
3645 1990-12-27  14.0     12   27  10.0  12.9  14.6  14.0
3646 1990-12-28  13.6     12   28  12.9  14.6  14.0  13.6
3647 1990-12-29  13.5     12   29  14.6  14.0  13.6  13.5
3648 1990-12-30  15.7     12   30  14.0  13.6  13.5  15.7
3649 1990-12-31  13.0     12   31  13.6  13.5  15.7  13.0

[3650 rows x 8 columns]